### ISSUE TITLE
Invalid signal files samplerate in examples

### ISSUE THREAD

**Issue by o-kos** [fventuri/navtex#1]
Raw files in examples directory has samplerate=11025 Hz, but in navtex_rx_from_file.cpp is
int sample_rate = 48000;

**Comment by fventuri** [comment]
Good point @o-kos - we were playing around with some sound files sampled at 48kHz when I committed the code, and I forgot to change the sample rate in `navtex_rx_from_file` back to 11025.

I just changed the `navtex_rx_from_file` program to read the sample rate of the input file from the first argument (the default value is 11025Hz).
I also added to the `README` a couple of examples showing how `navtex_rx_from_file` can be used to decode NAVTEX sound files sampled both at 11.025kHz and 48kHz (and possibly other sample rates, although we have tried only these two cases).

Franco
